import { createFileRoute } from "@tanstack/react-router";

import { KpiCard, Panel, PrototypeNotice, RiskBadge } from "@/components/aivora/primitives";
import { SimulationControl } from "@/components/aivora/SimulationControl";
import { LocationSelector } from "@/components/aivora/insight";
import { RealtimeAreaChart } from "@/components/aivora/charts";
import { useDistrictSummary, useSimulation } from "@/lib/aivora/store";
import { DEMO_SEQUENCE } from "@/lib/aivora/engine";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/_authenticated/simulation")({
  head: () => ({
    meta: [
      { title: "Simulation & Demo Mode — AIVORA" },
      {
        name: "description",
        content:
          "Drive the prototype: trigger heavy rain, soil saturation, river rise, flash flood, sensor failure and connectivity loss scenarios.",
      },
      { property: "og:title", content: "Simulation & Demo Mode — AIVORA" },
      {
        property: "og:description",
        content: "Guided demo and manual scenario controls for the AIVORA flash flood prototype.",
      },
    ],
  }),
  component: SimulationPage,
});

function SimulationPage() {
  const sim = useSimulation();
  const s = useDistrictSummary();
  const selected = sim.live[sim.selectedLocationId];

  const chart = (selected?.history ?? []).map((h, i) => ({
    label: `${i}`,
    probability: Math.round(h.probability),
    rainfall: Math.round(h.rainfall),
    river: Number(h.river.toFixed(2)),
  }));

  return (
    <div className="space-y-5">
      <header className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="font-display text-2xl font-bold">Simulation & Demo Mode</h1>
          <p className="text-xs text-muted-foreground">
            Every value in AIVORA is generated by this simulation engine — no live field data is connected
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <LocationSelector />
          <PrototypeNotice />
        </div>
      </header>

      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <KpiCard label="Engine" value={sim.running ? "RUNNING" : "PAUSED"} hint={`${sim.speed}× speed`} live={sim.running} />
        <KpiCard label="Scenario" value={sim.scenario.replace(/_/g, " ")} hint={`Tick ${sim.tick}`} />
        <KpiCard label="District risk" value={Math.round(s.maxProbability)} unit="%" level={s.worst?.prediction.riskLevel} live />
        <KpiCard label="Connectivity" value={sim.connectivity} live />
      </div>

      <div className="grid gap-4 xl:grid-cols-3">
        <div className="xl:col-span-2">
          <SimulationControl />
        </div>

        <div className="space-y-4">
          <Panel title="Guided demo sequence" subtitle="One-click narrative for evaluators">
            <ol className="space-y-2">
              {DEMO_SEQUENCE.map((step, i) => (
                <li
                  key={step.id}
                  className={cn(
                    "rounded-md border px-3 py-2 text-xs",
                    sim.demoRunning && sim.demoStage === i
                      ? "border-primary bg-primary/10 text-primary"
                      : "border-border bg-surface-2 text-muted-foreground",
                  )}
                >
                  <span className="metric mr-2">{i + 1}</span>
                  {step.label}
                </li>
              ))}
            </ol>
          </Panel>

          <Panel title="Current classification">
            {selected && (
              <div className="flex items-center justify-between">
                <span className="text-sm font-medium">{selected.location.name}</span>
                <RiskBadge level={selected.prediction.riskLevel} size="md" />
              </div>
            )}
            <p className="mt-2 text-xs text-muted-foreground">
              {selected?.prediction.explanation ?? "Waiting for the first prediction cycle."}
            </p>
          </Panel>
        </div>
      </div>

      <Panel title="Scenario response" subtitle="How probability, rainfall and river level react to your inputs">
        <RealtimeAreaChart
          data={chart}
          height={260}
          series={[
            { key: "probability", name: "Flood probability %", color: "var(--color-chart-4)" },
            { key: "rainfall", name: "Rainfall mm/hr", color: "var(--color-chart-1)" },
            { key: "river", name: "River level m", color: "var(--color-chart-3)" },
          ]}
        />
      </Panel>
    </div>
  );
}
